# Generated by Django 4.0.5 on 2022-06-25 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="product/productimage/", verbose_name="썸네일"
                    ),
                ),
                (
                    "full_image",
                    models.ImageField(
                        upload_to="product/productimage/", verbose_name="이미지"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("title", models.CharField(max_length=100, verbose_name="상품 이름")),
                ("description", models.TextField(verbose_name="상품 설명")),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="product.category",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "images",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상품 판매자",
                    ),
                ),
            ],
        ),
    ]
